# Generated by Django 6.0.3 on 2026-03-09 17:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedfinance_finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyBudget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.DateField(help_text='Use first day of month (YYYY-MM-01)')),
                ('income_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_by_user_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_budgets', to='sharedfinance_finance.sharedworkspace')),
            ],
            options={
                'db_table': 'monthly_budget',
                'ordering': ['-month', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('planned_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='sharedfinance_finance.monthlybudget')),
            ],
            options={
                'db_table': 'budget_category',
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='monthlybudget',
            constraint=models.UniqueConstraint(fields=('workspace', 'month'), name='unique_budget_per_workspace_month'),
        ),
        migrations.AddConstraint(
            model_name='monthlybudget',
            constraint=models.CheckConstraint(condition=models.Q(('income_amount__gt', 0)), name='income_amount_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='budgetcategory',
            constraint=models.UniqueConstraint(fields=('budget', 'name'), name='unique_budget_category_name'),
        ),
        migrations.AddConstraint(
            model_name='budgetcategory',
            constraint=models.CheckConstraint(condition=models.Q(('planned_amount__gte', 0)), name='planned_amount_gte_zero'),
        ),
    ]
