# Generated by Django 6.0.3 on 2026-03-09 18:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedfinance_finance', '0002_monthlybudget_budgetcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsgoal',
            name='created_by_user_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='transaction',
            name='created_by_user_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.CreateModel(
            name='SavingsContribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('contribution_date', models.DateField()),
                ('created_by_user_id', models.UUIDField()),
                ('created_by_user_email', models.EmailField(blank=True, default='', max_length=254)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('savings_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='sharedfinance_finance.savingsgoal')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_contributions', to='sharedfinance_finance.sharedworkspace')),
            ],
            options={
                'db_table': 'savings_contribution',
                'ordering': ['-contribution_date', '-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='contribution_amount_gt_zero')],
            },
        ),
    ]
