# Generated by Django 6.0.3 on 2026-03-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedfinance_finance', '0003_savingsgoal_created_by_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlybudget',
            name='is_shared',
            field=models.BooleanField(default=True, help_text='True=Aportacion compartida, False=Ingreso personal'),
        ),
        migrations.AddField(
            model_name='savingscontribution',
            name='is_shared',
            field=models.BooleanField(default=True, help_text='Hereda de savings_goal.is_shared'),
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='is_shared',
            field=models.BooleanField(default=True, help_text='True=Compartido (visible para todos), False=Personal (solo para el creador)'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_shared',
            field=models.BooleanField(default=True, help_text='True=Compartido (visible para todos), False=Personal (solo para el creador)'),
        ),
    ]
