# Generated by Django 6.0.3 on 2026-03-09 19:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedfinance_finance', '0004_monthlybudget_is_shared_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(help_text='WhatsApp phone with country code, e.g., +5215512345678', max_length=20, unique=True)),
                ('user_id', models.UUIDField(help_text='User ID from auth-service')),
                ('user_email', models.EmailField(blank=True, default='', max_length=254)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable bot access for this phone')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(help_text='Primary workspace for this WhatsApp user', on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_users', to='sharedfinance_finance.sharedworkspace')),
            ],
            options={
                'db_table': 'whatsapp_user',
                'ordering': ['phone_number'],
            },
        ),
    ]
