# Generated by Django 6.0.3 on 2026-03-09 18:23

import sharedfinance_auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedfinance_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedworkspace',
            name='invitation_code',
            field=models.CharField(db_index=True, default=sharedfinance_auth.models.generate_invitation_code, max_length=12),
        ),
    ]
